myApp/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

myApp/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
]

myApp/myApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myband.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myApp/myband/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'myband'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='band/login.html', authentication_form=LoginForm), name='login')
]

myApp/myband/models.py
from django.db import models

# Create your models here.

myApp/myband/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    """
    Form for user login.

    Inherits from Django's AuthenticationForm and adds placeholder attributes and CSS classes to the fields.

    Fields:
        - username: CharField for the username.
        - password: CharField for the password.

    Widgets:
        - username: TextInput widget with placeholder and CSS classes.
        - password: TextInput widget with placeholder and CSS classes.
    """
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    password = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

class SignupForm(UserCreationForm):
    """
    Form for user signup.

    Inherits from Django's UserCreationForm and adds placeholder attributes and CSS classes to the fields.

    Meta:
        model: The User model.
        fields: The fields to include in the form.

    Fields:
        - username: CharField for the username.
        - email: CharField for the email address.
        - password1: CharField for the password.
        - password2: CharField for password confirmation.

    Widgets:
        - username: TextInput widget with placeholder and CSS classes.
        - email: TextInput widget with placeholder and CSS classes.
        - password1: TextInput widget with placeholder and CSS classes.
        - password2: TextInput widget with placeholder and CSS classes.
    """
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your username',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        email = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your email address',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        password1 = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Your password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

        password2 = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'Confirm your password',
            'class': 'w-full py-4 px-6 rounded-xl'
        }))

myApp/myband/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from item.models import Category, Item
from .forms import SignupForm

# Create your views here.

def index(request):
    """
    Render the index page with a list of items and categories.

    Retrieves all items and categories from the database and passes them to the template.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """

    items = Item.objects.filter()
    categories = Category.objects.all()

    return render(request, 'band/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    """
    Render the contact page.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    return render(request, 'band/contact.html')

def signup(request):
    """
    Render the signup page and handle the signup form submission.

    If the request method is POST, validate the form data and create a new user account.
    If the form is valid, save the form and redirect to the login page.
    If there is an error, display an error message.
    If the request method is GET, display an empty signup form.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.
    """
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
             # Redirect to the login page
            messages.success(request, 'Account created successfully. You can now log in.')
            return redirect ('myband:login')
        else:
            messages.error(request, 'There was an error creating your account.')

    else:
        form = SignupForm()

    return render(request, 'band/signup.html', {
        'form': form
    })

myApp/myband/templates/band/base.html
<!doctype html>

<html>
    <head>
    <!-- add the Bootstrap CSS link -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    
    <!-- add other meta tags or scripts here -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Band</title>
    </head>

    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Band</a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'myband:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'myband:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
                {% endif %}
            </div>
        </nav>

       <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
       </div>

       <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pro-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500"> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Corporis placeat odio eveniet doloribus, quaerat expedita aliquam nobis dolore facere! Dolores porro maxime cupiditate tempore commodi dolor. Quas porro veniam unde.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-gray-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'myband:contact' %}" class="text-lg text-gray-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-gray-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-gray-500 hover:text-teal-700">Terms of use</a></li>
                </ul>
            </div>
       </footer>
    </body>
</html>

myApp/myband/templates/band/contact.html
{% extends 'band/base.html' %}

{% block tittle %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>

{% endblock %}

myApp/myband/templates/band/index.html
{% extends 'band/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Albums</h2>

        <div class="grid grid-cols-4 gap-3">
            {% for item in items %}
                <div>
                    <a href="#">
                        <div>
                            <img src="{{ items.images.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ items.artist }}</h2>
                            <p class="text-gray-500">Description: {{ item.description }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

myApp/myband/templates/band/login.html
{% extends 'band/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    {% if form.errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            <strong>{{ form.errors }}</strong>
        </div>
    {% endif %}

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><b></b>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Enter Password</label><b></b>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors  %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_erros }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

myApp/myband/templates/band/signup.html
{% extends 'band/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><b></b>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><b></b>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Enter Password</label><b></b>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><b></b>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors  %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in forms %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_erros }}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}